global using vabalas_api.Data;
global using Microsoft.EntityFrameworkCore;
using vabalas_api.Service;
using vabalas_api.Service.Impl;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.Filters;
using vabalas_api.Configs;


namespace vabalas_api
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);
            
            // Configs, DB, AutoGenerated
            builder.Configuration.AddConfiguration(EnvConfig.InitializeEnvironemnt());
            builder.Services.AddControllers();
            builder.Services.AddDbContext<DataContext>(options =>
            {
                options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection"));
            });
            builder.Services.AddEndpointsApiExplorer();
            builder.Services.AddAutoMapper(typeof(Program).Assembly);
            
            // Services
            builder.Services.AddScoped<IJwtService, JwtService>();
            builder.Services.AddScoped<IJobService, JobService>();
            builder.Services.AddScoped<IStatisticsService, StatisticsService>();
            builder.Services.AddScoped<IUserService,UserService>();
            builder.Services.AddScoped<IReviewService,ReviewSevice>();
            builder.Services.AddScoped<IJobOfferService, JobOfferService>();

            // Authentication
            builder.Services.AddAuthentication().AddJwtBearer();
            builder.Services.AddSwaggerGen(options =>
            {
                options.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
                {
                    In = ParameterLocation.Header,
                    Name = "Authorization",
                    Type = SecuritySchemeType.ApiKey
                });

                options.OperationFilter<SecurityRequirementsOperationFilter>();
            });

            var app = builder.Build();

            // Configure the HTTP request pipeline.
            if (app.Environment.IsDevelopment())
            {
                app.UseSwagger();
                app.UseSwaggerUI();
            }

            app.UseHttpsRedirection();
            app.UseAuthorization();
            app.MapControllers();
            app.Run();
        }
    }
}