global using vabalas_api.Data;
global using Microsoft.EntityFrameworkCore;
using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using vabalas_api.Repositories;
using vabalas_api.Repositories.Impl;
using vabalas_api.Service;
using vabalas_api.Service.Impl;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.Filters;
using vabalas_api.Configs;


namespace vabalas_api
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);
            
            // Configs, DB, AutoGenerated
            var config = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json")
                .Build();
            config["ConnectionStrings:DefaultConnection"] = config["ConnectionStrings:DefaultConnection"]!
                .Replace("{DB_SERVER}", Environment.GetEnvironmentVariable("DB_SERVER"))
                .Replace("{DB_NAME}", Environment.GetEnvironmentVariable("DB_NAME"));
            
            config["JwtSettings:Key"] = config["JwtSettings:Key"]!
                .Replace("{JWT_SECRET}", Environment.GetEnvironmentVariable("JWT_SECRET"));
            config["AppSettings:Token"] = config["AppSettings:Token"]!
                .Replace("{JWT_SECRET}", Environment.GetEnvironmentVariable("JWT_SECRET"));
            // builder.Configuration.AddConfiguration(EnvConfig.InitializeEnvironemnt());

            builder.Services.AddAuthentication(x =>
            {
                x.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                x.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                x.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
            }).AddJwtBearer(x =>
            {
                x.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidIssuer = config["JwtSettings:Issuer"],
                    ValidAudience = config["JwtSettings:Audience"],
                    IssuerSigningKey = new SymmetricSecurityKey
                        (Encoding.UTF8.GetBytes(config["JwtSettings:Key"])),
                    ValidateIssuer = true,
                    ValidateAudience = true,
                    ValidateLifetime = true,
                    ValidateIssuerSigningKey = true
                };
            });

            builder.Services.AddAuthorization();
            
            builder.Services.AddControllers();
            builder.Services.AddDbContext<DataContext>(options =>
            {
                options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection"));
            });
            builder.Services.AddEndpointsApiExplorer();
            builder.Services.AddAutoMapper(typeof(Program).Assembly);

            // Repositories
            builder.Services.AddScoped<IUserRepository, UserRepository>();
            builder.Services.AddScoped<IJobRepository, JobRepository>();
            builder.Services.AddScoped<IReviewRepository, ReviewRepository>();
            builder.Services.AddScoped<IJobOfferRepository, JobOfferRepository>();

            // Services
            builder.Services.AddScoped<IJwtService, JwtService>();
            builder.Services.AddScoped<IJobService, JobService>();
            builder.Services.AddScoped<IStatisticsService, StatisticsService>();
            builder.Services.AddScoped<IUserService,UserService>();
            builder.Services.AddScoped<IReviewService,ReviewSevice>();
            builder.Services.AddScoped<IJobOfferService, JobOfferService>();

            // Authentication
            // builder.Services.AddAuthentication().AddJwtBearer();
            
            builder.Services.AddSwaggerGen(options =>
            {
                options.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
                {
                    In = ParameterLocation.Header,
                    Name = "Authorization",
                    Type = SecuritySchemeType.ApiKey
                });

                options.OperationFilter<SecurityRequirementsOperationFilter>();
            });

            var app = builder.Build();

            // Configure the HTTP request pipeline.
            if (app.Environment.IsDevelopment())
            {
                app.UseSwagger();
                app.UseSwaggerUI();
            }

            app.UseHttpsRedirection();
            app.UseAuthentication();
            app.UseAuthorization();
            app.MapControllers();
            app.Run();
        }
    }
}